feat: add option labels
vitalics/playwright-prometheus-remote-write-reporter pull request #10
Opened 2024-08-11 18:52 UTC by xTrekStorex

This adds the option `labels` to the reporter, which implements the external_label behavior of prometheus remote write.
By default it's undefined and sets an empty array in prometheus-remote-write options, so there are no breaking changes.

Implements https://github.com/vitalics/playwright-prometheus-remote-write-reporter/issues/9

2024-08-12 20:05 UTC, vitalics commented
please make rebase(or merge) from current master

2024-08-14 11:12 UTC, xTrekStorex commented
> please make rebase(or merge) from current master

done

2024-08-15 09:22 UTC, xTrekStorex commented
regarding the build errors: I am no nodejs dev and never touched typescript. so I have no idea how to properly define an array of key value pairs as type. all the docs I read suggested `Record<string, string>[]` but that seems to be invalid.

the lib expects an array of key value pairs:
```
labels: Array.isArray(t.labels)
  ? [t.labels, ...(kv(options?.labels) || [])]
  : kv({
      ...options?.labels,
      ...t.labels,
    }),
```

2024-08-16 12:54 UTC, xTrekStorex commented
fixed and build tested locally

2024-08-16 21:37 UTC, vitalics requested changes

2024-08-16 21:37 UTC, vitalics commented on README.md
> +| labels        | Ext. labels for all metrics. E.g. `[{label1: 'value1'}]`  | undefined                            |
please update the example. It should be an object

2024-08-16 21:37 UTC, vitalics commented on src/index.ts
> +   * [{ instance: "hostname" }]
example and type missmatched

2024-08-18 17:19 UTC, vitalics approved these changes
LGTM!

2024-08-18 17:19 UTC, merged